"""Type stubs for CuPy library (CUDA-accelerated NumPy)."""

from collections.abc import Sequence
from typing import Any, Optional, TypeVar, Union

import numpy as np
from numpy.typing import ArrayLike, DTypeLike, NDArray

_T = TypeVar("_T")

class ndarray:
    """CuPy multi-dimensional array on GPU."""

    def __init__(
        self,
        shape: Union[int, Sequence[int]],
        dtype: DTypeLike = ...,
        memptr: Any = ...,
        strides: Optional[Sequence[int]] = ...,
        order: str = ...,
    ) -> None: ...

    # Conversion
    def get(self, stream: Any = ..., order: str = ..., out: Optional[NDArray[Any]] = ...) -> NDArray[Any]: ...
    def set(self, arr: ArrayLike, stream: Any = ...) -> None: ...
    def __array__(self, dtype: Optional[DTypeLike] = ...) -> NDArray[Any]: ...

    # Indexing
    def __getitem__(self, key: Any) -> ndarray: ...
    def __setitem__(self, key: Any, value: Any) -> None: ...

    # Properties
    @property
    def shape(self) -> tuple[int, ...]: ...
    @property
    def dtype(self) -> np.dtype[Any]: ...
    @property
    def size(self) -> int: ...
    @property
    def ndim(self) -> int: ...
    @property
    def strides(self) -> tuple[int, ...]: ...
    @property
    def nbytes(self) -> int: ...
    @property
    def T(self) -> ndarray: ...
    @property
    def data(self) -> Any: ...  # MemoryPointer

    # Shape manipulation
    def reshape(self, *shape: int, order: str = ...) -> ndarray: ...
    def transpose(self, *axes: int) -> ndarray: ...
    def ravel(self, order: str = ...) -> ndarray: ...
    def flatten(self, order: str = ...) -> ndarray: ...
    def squeeze(self, axis: Optional[Union[int, tuple[int, ...]]] = ...) -> ndarray: ...

    # Type conversion
    def astype(self, dtype: DTypeLike, order: str = ..., copy: bool = ...) -> ndarray: ...
    def view(self, dtype: Optional[DTypeLike] = ...) -> ndarray: ...
    def copy(self, order: str = ...) -> ndarray: ...

    # Arithmetic operators
    def __add__(self, other: Any) -> ndarray: ...
    def __sub__(self, other: Any) -> ndarray: ...
    def __mul__(self, other: Any) -> ndarray: ...
    def __truediv__(self, other: Any) -> ndarray: ...
    def __floordiv__(self, other: Any) -> ndarray: ...
    def __mod__(self, other: Any) -> ndarray: ...
    def __pow__(self, other: Any) -> ndarray: ...
    def __neg__(self) -> ndarray: ...

    # Comparison operators
    def __lt__(self, other: Any) -> ndarray: ...
    def __le__(self, other: Any) -> ndarray: ...
    def __gt__(self, other: Any) -> ndarray: ...
    def __ge__(self, other: Any) -> ndarray: ...
    def __eq__(self, other: Any) -> ndarray: ...  # type: ignore[override]
    def __ne__(self, other: Any) -> ndarray: ...  # type: ignore[override]

    # Reduction methods
    def sum(
        self, axis: Optional[Union[int, tuple[int, ...]]] = ..., dtype: DTypeLike = ..., keepdims: bool = ...
    ) -> Union[ndarray, Any]: ...
    def mean(
        self, axis: Optional[Union[int, tuple[int, ...]]] = ..., dtype: DTypeLike = ..., keepdims: bool = ...
    ) -> Union[ndarray, Any]: ...
    def std(
        self, axis: Optional[Union[int, tuple[int, ...]]] = ..., dtype: DTypeLike = ..., keepdims: bool = ..., ddof: int = ...
    ) -> Union[ndarray, Any]: ...
    def max(self, axis: Optional[Union[int, tuple[int, ...]]] = ..., keepdims: bool = ...) -> Union[ndarray, Any]: ...
    def min(self, axis: Optional[Union[int, tuple[int, ...]]] = ..., keepdims: bool = ...) -> Union[ndarray, Any]: ...

# Array creation functions
def array(obj: ArrayLike, dtype: Optional[DTypeLike] = ..., copy: bool = ..., order: str = ..., ndmin: int = ...) -> ndarray: ...
def asarray(a: Any, dtype: Optional[DTypeLike] = ..., order: str = ...) -> ndarray: ...
def ascontiguousarray(a: Any, dtype: Optional[DTypeLike] = ...) -> ndarray: ...
def zeros(shape: Union[int, Sequence[int]], dtype: DTypeLike = ..., order: str = ...) -> ndarray: ...
def ones(shape: Union[int, Sequence[int]], dtype: DTypeLike = ..., order: str = ...) -> ndarray: ...
def empty(shape: Union[int, Sequence[int]], dtype: DTypeLike = ..., order: str = ...) -> ndarray: ...
def full(shape: Union[int, Sequence[int]], fill_value: Any, dtype: Optional[DTypeLike] = ..., order: str = ...) -> ndarray: ...
def zeros_like(
    a: ndarray, dtype: Optional[DTypeLike] = ..., order: str = ..., shape: Optional[Sequence[int]] = ...
) -> ndarray: ...
def ones_like(
    a: ndarray, dtype: Optional[DTypeLike] = ..., order: str = ..., shape: Optional[Sequence[int]] = ...
) -> ndarray: ...
def empty_like(
    a: ndarray, dtype: Optional[DTypeLike] = ..., order: str = ..., shape: Optional[Sequence[int]] = ...
) -> ndarray: ...
def arange(start: Any, stop: Optional[Any] = ..., step: Any = ..., dtype: Optional[DTypeLike] = ...) -> ndarray: ...
def linspace(
    start: Any, stop: Any, num: int = ..., endpoint: bool = ..., retstep: bool = ..., dtype: Optional[DTypeLike] = ...
) -> Union[ndarray, tuple[ndarray, Any]]: ...

# Mathematical functions
def sum(
    a: ndarray, axis: Optional[Union[int, tuple[int, ...]]] = ..., dtype: DTypeLike = ..., keepdims: bool = ...
) -> Union[ndarray, Any]: ...
def mean(
    a: ndarray, axis: Optional[Union[int, tuple[int, ...]]] = ..., dtype: DTypeLike = ..., keepdims: bool = ...
) -> Union[ndarray, Any]: ...
def std(
    a: ndarray, axis: Optional[Union[int, tuple[int, ...]]] = ..., dtype: DTypeLike = ..., keepdims: bool = ..., ddof: int = ...
) -> Union[ndarray, Any]: ...
def var(
    a: ndarray, axis: Optional[Union[int, tuple[int, ...]]] = ..., dtype: DTypeLike = ..., keepdims: bool = ..., ddof: int = ...
) -> Union[ndarray, Any]: ...
def max(a: ndarray, axis: Optional[Union[int, tuple[int, ...]]] = ..., keepdims: bool = ...) -> Union[ndarray, Any]: ...
def min(a: ndarray, axis: Optional[Union[int, tuple[int, ...]]] = ..., keepdims: bool = ...) -> Union[ndarray, Any]: ...
def abs(x: ndarray) -> ndarray: ...
def sqrt(x: ndarray) -> ndarray: ...
def exp(x: ndarray) -> ndarray: ...
def log(x: ndarray) -> ndarray: ...
def sin(x: ndarray) -> ndarray: ...
def cos(x: ndarray) -> ndarray: ...
def clip(a: ndarray, a_min: Any, a_max: Any, out: Optional[ndarray] = ...) -> ndarray: ...

# Linear algebra
def dot(a: ndarray, b: ndarray, out: Optional[ndarray] = ...) -> ndarray: ...
def matmul(a: ndarray, b: ndarray, out: Optional[ndarray] = ...) -> ndarray: ...
def tensordot(a: ndarray, b: ndarray, axes: Any = ...) -> ndarray: ...

# FFT functions
def fft2(a: ndarray, s: Optional[Sequence[int]] = ..., axes: tuple[int, int] = ..., norm: Optional[str] = ...) -> ndarray: ...
def ifft2(a: ndarray, s: Optional[Sequence[int]] = ..., axes: tuple[int, int] = ..., norm: Optional[str] = ...) -> ndarray: ...
def fft(a: ndarray, n: Optional[int] = ..., axis: int = ..., norm: Optional[str] = ...) -> ndarray: ...
def ifft(a: ndarray, n: Optional[int] = ..., axis: int = ..., norm: Optional[str] = ...) -> ndarray: ...

# Shape manipulation
def reshape(a: ndarray, newshape: Union[int, Sequence[int]], order: str = ...) -> ndarray: ...
def transpose(a: ndarray, axes: Optional[Sequence[int]] = ...) -> ndarray: ...
def concatenate(arrays: Sequence[ndarray], axis: int = ..., out: Optional[ndarray] = ...) -> ndarray: ...
def stack(arrays: Sequence[ndarray], axis: int = ..., out: Optional[ndarray] = ...) -> ndarray: ...
def squeeze(a: ndarray, axis: Optional[Union[int, tuple[int, ...]]] = ...) -> ndarray: ...

# Device management
def cuda_runtime_version() -> int: ...
def get_default_memory_pool() -> MemoryPool: ...
def get_default_pinned_memory_pool() -> PinnedMemoryPool: ...

class MemoryPool:
    """GPU memory pool."""

    def used_bytes(self) -> int: ...
    def total_bytes(self) -> int: ...
    def free_all_blocks(self, stream: Any = ...) -> None: ...

class PinnedMemoryPool:
    """Pinned (page-locked) memory pool."""

    def n_free_blocks(self) -> int: ...
    def free_all_blocks(self) -> None: ...

class cuda:
    """CUDA-related utilities."""

    class Device:
        def __init__(self, device_id: int = ...) -> None: ...
        def use(self) -> None: ...
        def __enter__(self) -> cuda.Device: ...
        def __exit__(self, *args: Any) -> None: ...

    class Stream:
        def __init__(self, null: bool = ..., non_blocking: bool = ...) -> None: ...
        def synchronize(self) -> None: ...
        def __enter__(self) -> cuda.Stream: ...
        def __exit__(self, *args: Any) -> None: ...

    @staticmethod
    def runtime_version() -> int: ...

def __getattr__(name: str) -> Any: ...
