"""Type stubs for skimage.color module."""

from typing import Any

import numpy as np
from numpy.typing import NDArray

def rgb2gray(rgb: NDArray[Any]) -> NDArray[np.floating[Any]]: ...
def gray2rgb(image: NDArray[Any]) -> NDArray[Any]: ...
def rgb2hsv(rgb: NDArray[Any]) -> NDArray[np.floating[Any]]: ...
def hsv2rgb(hsv: NDArray[Any]) -> NDArray[Any]: ...
def rgb2lab(rgb: NDArray[Any]) -> NDArray[np.floating[Any]]: ...
def lab2rgb(lab: NDArray[Any]) -> NDArray[Any]: ...
def __getattr__(name: str) -> Any: ...
