"""Type stubs for SMBus library."""

from typing import Any

class SMBus:
    def __init__(self, bus: int = ...) -> None: ...
    def open(self, bus: int) -> None: ...
    def close(self) -> None: ...
    def read_byte(self, addr: int) -> int: ...
    def read_byte_data(self, addr: int, cmd: int) -> int: ...
    def read_word_data(self, addr: int, cmd: int) -> int: ...
    def read_block_data(self, addr: int, cmd: int) -> list[int]: ...
    def write_byte(self, addr: int, val: int) -> None: ...
    def write_byte_data(self, addr: int, cmd: int, val: int) -> None: ...
    def write_word_data(self, addr: int, cmd: int, val: int) -> None: ...
    def write_block_data(self, addr: int, cmd: int, vals: list[int]) -> None: ...

def __getattr__(name: str) -> Any: ...
