"""Type stubs for SMBus library (I2C communication)."""

from typing import Any, Optional, Protocol
from collections.abc import Sequence

class SMBusProtocol(Protocol):
    """Protocol interface for SMBus-compatible implementations."""

    def read_byte(self, addr: int) -> int: ...
    def read_byte_data(self, addr: int, cmd: int) -> int: ...
    def write_byte(self, addr: int, val: int) -> None: ...
    def write_byte_data(self, addr: int, cmd: int, val: int) -> None: ...

class SMBus:
    """SMBus/I2C interface for communication with I2C devices."""

    def __init__(self, bus: int = ...) -> None: ...
    def open(self, bus: int) -> None: ...
    def close(self) -> None: ...

    # Quick commands
    def write_quick(self, addr: int) -> None: ...

    # Byte operations
    def read_byte(self, addr: int) -> int: ...
    def write_byte(self, addr: int, val: int) -> None: ...

    # Byte data operations
    def read_byte_data(self, addr: int, cmd: int) -> int: ...
    def write_byte_data(self, addr: int, cmd: int, val: int) -> None: ...

    # Word data operations
    def read_word_data(self, addr: int, cmd: int) -> int: ...
    def write_word_data(self, addr: int, cmd: int, val: int) -> None: ...

    # Process call
    def process_call(self, addr: int, cmd: int, val: int) -> int: ...

    # Block operations
    def read_block_data(self, addr: int, cmd: int) -> list[int]: ...
    def write_block_data(self, addr: int, cmd: int, vals: Sequence[int]) -> None: ...

    # I2C block operations
    def read_i2c_block_data(self, addr: int, cmd: int, length: int = ...) -> list[int]: ...
    def write_i2c_block_data(self, addr: int, cmd: int, vals: Sequence[int]) -> None: ...

    # I2C read/write combined
    def i2c_rdwr(self, *msgs: i2c_msg) -> None: ...

    # PEC (Packet Error Checking)
    pec: bool

class i2c_msg:
    """I2C message for combined read/write operations."""

    addr: int
    flags: int
    len: int
    buf: bytes

    def __init__(self, addr: int, flags: int, buf: Optional[bytes] = ...) -> None: ...
    @staticmethod
    def read(addr: int, length: int) -> i2c_msg: ...
    @staticmethod
    def write(addr: int, buf: bytes) -> i2c_msg: ...

# I2C flags
I2C_M_RD: int
I2C_M_TEN: int
I2C_M_NOSTART: int
I2C_M_REV_DIR_ADDR: int
I2C_M_IGNORE_NAK: int
I2C_M_NO_RD_ACK: int

def __getattr__(name: str) -> Any: ...
